In [66]:
import pandas as pd
import numpy as np 
import cv2

In [67]:
df=pd.read_csv("Crop_details.csv")
test=df.sample(10)
test

Unnamed: 0                                               path       crop  \
78           78  /kaggle/input/kag2/sugarcane/sugarcane026ahs.jpeg  sugarcane   
991         991       /kaggle/input/crop_images/rice/rice026a.jpeg       rice   
26           26  /kaggle/input/kag2/sugarcane/sugarcane028ahs.jpeg  sugarcane   
404         404              /kaggle/input/kag2/jute/jute027a.jpeg       jute   
467         467            /kaggle/input/kag2/jute/jute008ahs.jpeg       jute   
570         570         /kaggle/input/kag2/maize/maize030arot.jpeg      maize   
359         359            /kaggle/input/kag2/jute/jute008ahf.jpeg       jute   
510         510            /kaggle/input/kag2/maize/maize037a.jpeg      maize   
909         909       /kaggle/input/crop_images/jute/jute025a.jpeg       jute   
857         857     /kaggle/input/crop_images/wheat/wheat005a.jpeg      wheat   

     croplabel                                             path1  
78           3  kaggle/input/kag2/sugarcane/sugarcane026ahs.jpeg  
991          2       kaggle/input/crop_images/rice/rice026a.jpeg  
26           3  kaggle/input/kag2/sugarcane/sugarcane028ahs.jpeg  
404          0              kaggle/input/kag2/jute/jute027a.jpeg  
467          0            kaggle/input/kag2/jute/jute008ahs.jpeg  
570          1         kaggle/input/kag2/maize/maize030arot.jpeg  
359          0            kaggle/input/kag2/jute/jute008ahf.jpeg  
510          1            kaggle/input/kag2/maize/maize037a.jpeg  
909          0       kaggle/input/crop_images/jute/jute025a.jpeg  
857          4     kaggle/input/crop_images/wheat/wheat005a.jpeg

In [68]:
image_array_list=[]
# img = cv2.imread(img_path)
# print(img.shape)
for img_path in df['path1']:
    img = cv2.imread(img_path)
    # print(img)
    if img is not None:
        # img = cv2.resize(img, (64, 64))
        image_array_list.append(img)
# img_path="kaggle/input/crop_images/jute/jute001a.jpeg"
# img1=cv2.imread(img_path)
image_array = np.array(image_array_list)   #input cols
image_array.shape

(999, 224, 224, 3)

In [69]:
# image_array=color_hist_features
# image_array=color_hist_features
Y=df['croplabel']
image_array.shape
from sklearn.model_selection import train_test_split
X_train_val, X_test, Y_train_val, Y_test =train_test_split(image_array,Y,random_state=42)
X_train, X_val, Y_train, Y_val = train_test_split(X_train_val, Y_train_val,random_state=42)

In [70]:
# import cv2
# import numpy as np

# # Example for a single image (you can loop through your dataset)
# color_hist_features = []
# for img in image_array:
#     # Split the image into color channels
#     channels = cv2.split(img)

#     #  if len(image.shape) == 2:  # If the image is grayscale (2D)
#     #     image = cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)  # Convert to 3-channel RGB
#     # image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
#     # Compute histograms for each channel
#     hist_r = cv2.calcHist([channels[0]], [0], None, [256], [0, 256])
#     hist_g = cv2.calcHist([channels[1]], [0], None, [256], [0, 256])
#     hist_b = cv2.calcHist([channels[2]], [0], None, [256], [0, 256])
    
#     # Flatten the histograms into a feature vector
#     color_hist_features.append(np.concatenate([hist_r.flatten(), hist_g.flatten(), hist_b.flatten()]))

# # Convert list to numpy array
# color_hist_features = np.array(color_hist_features)

# print(color_hist_features.shape)  # Shape will depend on the number of bins

In [71]:
import numpy as np
import cv2  # OpenCV for image processing

def extract_color_histogram(image, bins=(8, 8, 8)):
    # Convert image to HSV
    if image.dtype != np.uint8:
        image = (image * 255).astype(np.uint8)  # or just image.astype(np.uint8) if already in 0–255

    hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)
    # Calculate the color histogram
    hist = cv2.calcHist([hsv], [0, 1, 2], None, bins,
                        [0, 180, 0, 256, 0, 256])
    # Normalize and flatten
    cv2.normalize(hist, hist)
    return hist.flatten()

In [72]:
X_train = np.array([extract_color_histogram(img) for img in X_train])
X_val = np.array([extract_color_histogram(img) for img in X_val])
X_test = np.array([extract_color_histogram(img) for img in X_test])
# X_train.shape

In [73]:
# from sklearn.decomposition import PCA
# pca = PCA(n_components=0.95)  # keep 95% variance, or set n_components=number like 50
# X_train = pca.fit_transform(X_train)

# # Use the same fitted PCA to transform validation and test
# X_val = pca.transform(X_val)
# X_test= pca.transform(X_test)
X_train.shape

(561, 512)

In [74]:
# hog_features=pca1.fit_transform(hog_features)
# color_hist_features=pca2.fit_transform(color_hist_features)
# Xtest=pca.transform(X_test)
# Xtrain.shape
# X_train.shape

In [75]:
# pca2.explained_variance_ratio_
# cumulative_variance = np.cumsum(pca2.explained_variance_ratio_)
# cumulative_variance

In [76]:
# image_array=np.hstack((lbp_features,color_hist_features,fourier_features,haralick_features,hog_features))
# image_array=np.hstack((lbp_features,color_hist_features))


In [77]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [78]:
X_train=scaler.fit_transform(X_train)
X_val=scaler.transform(X_val)
X_test=scaler.transform(X_test)

In [79]:
from sklearn.tree import DecisionTreeClassifier
clf1=DecisionTreeClassifier(max_depth=15,criterion='gini')
dt=clf1

In [80]:
import time
timestart=time.time()

clf1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=clf1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix
print(accuracy_score(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))

0.13546395301818848
0.007047891616821289
0.96
[[53  0  0  0  0]
 [ 0 50  1  1  2]
 [ 2  1 34  0  3]
 [ 0  0  0 52  0]
 [ 0  0  0  0 51]]


In [81]:
Y_pred=clf1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=clf1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.9414893617021277
1.0


In [82]:
from sklearn.neighbors import KNeighborsClassifier
clf1=KNeighborsClassifier()
knn=clf1
timestart=time.time()
clf1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=clf1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)

0.005901813507080078
0.10045123100280762


In [83]:
print(accuracy_score(Y_test,Y_pred))
Y_pred=clf1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=clf1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.776
0.7287234042553191
0.9144385026737968


In [84]:
from sklearn.linear_model import LogisticRegression
clf1=LogisticRegression()
logi=clf1

In [85]:
timestart=time.time()
clf1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=clf1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

0.1744861602783203
0.0021791458129882812
0.984


In [86]:
Y_pred=clf1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=clf1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.973404255319149
1.0


In [87]:
from sklearn.svm import SVC
clf1=SVC(C=2.5)
svm=clf1

In [88]:
timestart=time.time()
clf1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=clf1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
# print(clf1.predict(image1_array))
print(accuracy_score(Y_test,Y_pred))

0.06827306747436523
0.04162335395812988
0.872


In [89]:
Y_pred=clf1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=clf1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.8776595744680851
0.9393939393939394


In [90]:
from sklearn.naive_bayes import GaussianNB
clf1=GaussianNB()
nb=clf1
timestart=time.time()
clf1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=clf1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

0.014337539672851562
0.005042076110839844
0.632


In [91]:
Y_pred=clf1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=clf1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.5851063829787234
0.6381461675579323


In [92]:
from sklearn.ensemble import VotingClassifier

In [93]:
estimators=[('dt',dt),('svm',svm),('logi',logi),('knn',knn),('nb',nb)]

In [94]:
vt_clf1=VotingClassifier(estimators=estimators,weights=[1.5,1,1.5,0.5,0.5])
vt_clf1.fit(X_train,Y_train)
Y_pred=vt_clf1.predict(X_test)
print(accuracy_score(Y_test,Y_pred))
print(precision_score(Y_test,Y_pred,average='macro'))
print(recall_score(Y_test,Y_pred,average='macro'))
print(f1_score(Y_test,Y_pred,average='macro'))

0.984
0.9850454227812719
0.9849002849002849
0.9848248701189878


In [95]:
Y_pred=vt_clf1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
print(precision_score(Y_val,Y_pred,average='macro'))
print(recall_score(Y_val,Y_pred,average='macro'))
print(f1_score(Y_val,Y_pred,average='macro'))


0.9627659574468085
0.9628868755650452
0.9657850707850708
0.9635490954563813


In [96]:
Y_pred=vt_clf1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))
print(precision_score(Y_train,Y_pred,average='macro'))
print(recall_score(Y_train,Y_pred,average='macro'))
print(f1_score(Y_train,Y_pred,average='macro'))

1.0
1.0
1.0
1.0


In [97]:
from sklearn.ensemble import BaggingClassifier
dt1=BaggingClassifier(n_estimators=50,max_samples=0.9,max_features=0.9)
timestart=time.time()
dt1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=dt1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

3.183307409286499
0.0603940486907959
0.988


In [98]:
Y_pred=dt1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=dt1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.9840425531914894
1.0


In [99]:
svm1=BaggingClassifier(estimator=SVC(C=2.5),n_estimators=50,max_samples=0.9,max_features=0.9)
timestart=time.time()
svm1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=svm1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

2.267946481704712
1.0942878723144531
0.864


In [100]:
Y_pred=svm1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=svm1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.851063829787234
0.928698752228164


In [101]:
logi1=BaggingClassifier(estimator=LogisticRegression(),n_estimators=50,max_samples=0.9,max_features=0.9)
timestart=time.time()
logi1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=logi1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

4.6120946407318115
0.06355690956115723
0.984


In [102]:
Y_pred=logi1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=logi1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.973404255319149
1.0


In [103]:
from sklearn.ensemble import RandomForestClassifier
rf1=RandomForestClassifier(n_estimators=50,max_samples=0.9,max_features=0.9,max_depth=15,criterion='gini')

In [104]:
timestart=time.time()
rf1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=rf1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

1.9166297912597656
0.004569530487060547
0.988


In [105]:
Y_pred=rf1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=rf1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.9840425531914894
1.0


In [106]:
from sklearn.ensemble import AdaBoostClassifier
ab1=AdaBoostClassifier(n_estimators=100,learning_rate=0.1)
timestart=time.time()
ab1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=ab1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

C:\Users\dss28\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


1.2785792350769043
0.0275421142578125
0.668


In [107]:
Y_pred=ab1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=ab1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.6170212765957447
0.7415329768270945


In [108]:
from sklearn.ensemble import GradientBoostingClassifier
gb1=GradientBoostingClassifier(n_estimators=100,subsample=0.9,max_features=0.9)
timestart=time.time()
gb1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=gb1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

11.792886734008789
0.018161773681640625
0.988


In [109]:
Y_pred=gb1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=gb1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.9680851063829787
1.0


In [110]:
from xgboost import XGBClassifier
xb1=XGBClassifier(n_estimators=100,subsample=0.9,max_features=0.9)
timestart=time.time()
xb1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=xb1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

C:\Users\dss28\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [19:02:33] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "max_features" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


2.0214314460754395
0.005002021789550781
0.984


In [111]:
Y_pred=xb1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=xb1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.9680851063829787
1.0


In [112]:
# Y_pred=xb1.predict(X_train)
# print(accuracy_score(Y_train,Y_test))

In [113]:
estimators=[('dt1',dt1),('svm1',svm1),('logi1',logi1),('rf1',rf1),('ab1',ab1),('gb1',gb1),('xb1',xb1)]

In [114]:
vt_clf2=VotingClassifier(estimators=estimators,weights=[1.5,1,1.5,1.5,0.5,1.5,1.5)
vt_clf2.fit(X_train,Y_train)
Y_pred=vt_clf2.predict(X_test)
print(accuracy_score(Y_test,Y_pred))
print(precision_score(Y_test,Y_pred,average='macro'))
print(recall_score(Y_test,Y_pred,average='macro'))
print(f1_score(Y_test,Y_pred,average='macro'))

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (4234848899.py, line 1)

In [ ]:
Y_pred=vt_clf2.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
print(precision_score(Y_val,Y_pred,average='macro'))
print(recall_score(Y_val,Y_pred,average='macro'))
print(f1_score(Y_val,Y_pred,average='macro'))


In [ ]:
# recall_score,f1_score,confusion_matrix
Y_pred=vt_clf2.predict(X_train)
print(accuracy_score(Y_train,Y_pred))
print(precision_score(Y_train,Y_pred,average='macro'))
print(recall_score(Y_train,Y_pred,average='macro'))
print(f1_score(Y_train,Y_pred,average='macro'))

In [ ]:
test_array_list=[]
for test_path in test['path1']:
    test = cv2.imread(test_path)
    # print(img)
    if test is not None:
        # img = cv2.resize(img, (64, 64))
        test_array_list.append(test)
# img_path="kaggle/input/crop_images/jute/jute001a.jpeg"
# img1=cv2.imread(img_path)
test_array = np.array(test_array_list)   #input cols
test_array.shape

In [ ]:
# test=X_test.sample(5)
test_array=np.array([extract_color_histogram(img) for img in test_array])
test_array=scaler.transform(test_array)
vt_clf2.predict(test_array)

In [ ]:
test1=pd.read_csv("test.csv")
test1

In [ ]:
test1_array_list=[]
for test1_path in test1['path']:
    test1 = cv2.imread(test1_path)
    # print(img)
    if test1 is not None:
        test1 = cv2.resize(test1, (64, 64))
        test1_array_list.append(test1)
test1_array = np.array(test1_array_list)

In [ ]:
test1_array=np.array([extract_color_histogram(img) for img in test1_array])

In [ ]:
test1_array=scaler.transform(test1_array)
# test1_array

In [ ]:
vt_clf2.predict(test1_array)

In [ ]:
# jute_path="jute1.jpeg"
jute1=cv2.imread("jute1.jpeg")
jute1=cv2.resize(jute1,(224,224))
jute2=cv2.imread("jute2.jpeg")
jute2=cv2.resize(jute2,(224,224))
jute=[jute1,jute2]
jute_array=np.array(jute)

In [ ]:
jute_array=np.array([extract_color_histogram(img) for img in jute_array])

In [ ]:
jute_array=scaler.transform(jute_array)
vt_clf2.predict(jute_array)