In [71]:
import pandas as pd
import numpy as np 
import cv2

In [72]:
df=pd.read_csv("Crop_details.csv")
test=df.sample(10)
test

Unnamed: 0                                               path       crop  \
226         226          /kaggle/input/kag2/wheat/wheat025ahs.jpeg      wheat   
144         144    /kaggle/input/kag2/sugarcane/sugarcane015a.jpeg  sugarcane   
170         170            /kaggle/input/kag2/wheat/wheat037a.jpeg      wheat   
450         450            /kaggle/input/kag2/jute/jute006ahs.jpeg       jute   
821         821  /kaggle/input/crop_images/sugarcane/sugarcane0...  sugarcane   
161         161            /kaggle/input/kag2/wheat/wheat004a.jpeg      wheat   
405         405           /kaggle/input/kag2/jute/jute014arot.jpeg       jute   
299         299         /kaggle/input/kag2/wheat/wheat016arot.jpeg      wheat   
402         402            /kaggle/input/kag2/jute/jute013ahf.jpeg       jute   
296         296         /kaggle/input/kag2/wheat/wheat024arot.jpeg      wheat   

     croplabel                                              path1  
226          4           kaggle/input/kag2/wheat/wheat025ahs.jpeg  
144          3     kaggle/input/kag2/sugarcane/sugarcane015a.jpeg  
170          4             kaggle/input/kag2/wheat/wheat037a.jpeg  
450          0             kaggle/input/kag2/jute/jute006ahs.jpeg  
821          3  kaggle/input/crop_images/sugarcane/sugarcane00...  
161          4             kaggle/input/kag2/wheat/wheat004a.jpeg  
405          0            kaggle/input/kag2/jute/jute014arot.jpeg  
299          4          kaggle/input/kag2/wheat/wheat016arot.jpeg  
402          0             kaggle/input/kag2/jute/jute013ahf.jpeg  
296          4          kaggle/input/kag2/wheat/wheat024arot.jpeg

In [73]:
image_array_list=[]
# img = cv2.imread(img_path)
# print(img.shape)
for img_path in df['path1']:
    img = cv2.imread(img_path)
    # print(img)
    if img is not None:
        # img = cv2.resize(img, (64, 64))
        image_array_list.append(img)
# img_path="kaggle/input/crop_images/jute/jute001a.jpeg"
# img1=cv2.imread(img_path)
image_array = np.array(image_array_list)   #input cols
image_array.shape

(999, 224, 224, 3)

In [74]:
# image_array=color_hist_features
# image_array=color_hist_features
Y=df['croplabel']
image_array.shape
from sklearn.model_selection import train_test_split
X_train_val, X_test, Y_train_val, Y_test =train_test_split(image_array,Y,random_state=42)
X_train, X_val, Y_train, Y_val = train_test_split(X_train_val, Y_train_val,random_state=42)

In [75]:
# import cv2
# import numpy as np

# # Example for a single image (you can loop through your dataset)
# color_hist_features = []
# for img in image_array:
#     # Split the image into color channels
#     channels = cv2.split(img)

#     #  if len(image.shape) == 2:  # If the image is grayscale (2D)
#     #     image = cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)  # Convert to 3-channel RGB
#     # image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
#     # Compute histograms for each channel
#     hist_r = cv2.calcHist([channels[0]], [0], None, [256], [0, 256])
#     hist_g = cv2.calcHist([channels[1]], [0], None, [256], [0, 256])
#     hist_b = cv2.calcHist([channels[2]], [0], None, [256], [0, 256])
    
#     # Flatten the histograms into a feature vector
#     color_hist_features.append(np.concatenate([hist_r.flatten(), hist_g.flatten(), hist_b.flatten()]))

# # Convert list to numpy array
# color_hist_features = np.array(color_hist_features)

# print(color_hist_features.shape)  # Shape will depend on the number of bins

In [76]:
import numpy as np
import cv2  # OpenCV for image processing

def extract_color_histogram(image, bins=(8, 8, 8)):
    # Convert image to HSV
    if image.dtype != np.uint8:
        image = (image * 255).astype(np.uint8)  # or just image.astype(np.uint8) if already in 0–255

    hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)
    # Calculate the color histogram
    hist = cv2.calcHist([hsv], [0, 1, 2], None, bins,
                        [0, 180, 0, 256, 0, 256])
    # Normalize and flatten
    cv2.normalize(hist, hist)
    return hist.flatten()

In [77]:
X_train = np.array([extract_color_histogram(img) for img in X_train])
X_val = np.array([extract_color_histogram(img) for img in X_val])
X_test = np.array([extract_color_histogram(img) for img in X_test])
# X_train.shape

In [78]:
# from sklearn.decomposition import PCA
# pca = PCA(n_components=0.95)  # keep 95% variance, or set n_components=number like 50
# X_train = pca.fit_transform(X_train)

# # Use the same fitted PCA to transform validation and test
# X_val = pca.transform(X_val)
# X_test= pca.transform(X_test)
X_train.shape

(561, 512)

In [79]:
# hog_features=pca1.fit_transform(hog_features)
# color_hist_features=pca2.fit_transform(color_hist_features)
# Xtest=pca.transform(X_test)
# Xtrain.shape
# X_train.shape

In [80]:
# pca2.explained_variance_ratio_
# cumulative_variance = np.cumsum(pca2.explained_variance_ratio_)
# cumulative_variance

In [81]:
# image_array=np.hstack((lbp_features,color_hist_features,fourier_features,haralick_features,hog_features))
# image_array=np.hstack((lbp_features,color_hist_features))


In [82]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [83]:
X_train=scaler.fit_transform(X_train)
X_val=scaler.transform(X_val)
X_test=scaler.transform(X_test)

In [84]:
from sklearn.tree import DecisionTreeClassifier
clf1=DecisionTreeClassifier(max_depth=15,criterion='gini')
dt=clf1

In [85]:
import time
timestart=time.time()

clf1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=clf1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix
print(accuracy_score(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))

0.138136625289917
0.005757570266723633
0.96
[[52  0  1  0  0]
 [ 0 50  1  2  1]
 [ 0  2 36  0  2]
 [ 0  0  0 52  0]
 [ 0  0  0  1 50]]


In [86]:
Y_pred=clf1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=clf1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.9148936170212766
1.0


In [87]:
from sklearn.neighbors import KNeighborsClassifier
clf1=KNeighborsClassifier()
knn=clf1
timestart=time.time()
clf1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=clf1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)

0.005135297775268555
0.1739344596862793


In [88]:
print(accuracy_score(Y_test,Y_pred))
Y_pred=clf1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=clf1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.776
0.7287234042553191
0.9144385026737968


In [89]:
from sklearn.linear_model import LogisticRegression
clf1=LogisticRegression()
logi=clf1

In [90]:
timestart=time.time()
clf1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=clf1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

0.15274643898010254
0.0010006427764892578
0.984


In [91]:
Y_pred=clf1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=clf1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.973404255319149
1.0


In [92]:
from sklearn.svm import SVC
clf1=SVC(C=2.5)
svm=clf1

In [93]:
timestart=time.time()
clf1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=clf1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
# print(clf1.predict(image1_array))
print(accuracy_score(Y_test,Y_pred))

0.06672930717468262
0.037514448165893555
0.872


In [94]:
Y_pred=clf1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=clf1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.8776595744680851
0.9393939393939394


In [95]:
from sklearn.naive_bayes import GaussianNB
clf1=GaussianNB()
nb=clf1
timestart=time.time()
clf1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=clf1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

0.010118961334228516
0.005278825759887695
0.632


In [96]:
Y_pred=clf1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=clf1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.5851063829787234
0.6381461675579323


In [97]:
from sklearn.ensemble import VotingClassifier

In [98]:
estimators=[('dt',dt),('svm',svm),('logi',logi),('knn',knn),('nb',nb)]

In [99]:
vt_clf1=VotingClassifier(estimators=estimators,weights=[1.5,1,1.5,0.5,0.5])
vt_clf1.fit(X_train,Y_train)
Y_pred=vt_clf1.predict(X_test)
print(accuracy_score(Y_test,Y_pred))
print(precision_score(Y_test,Y_pred,average='macro'))
print(recall_score(Y_test,Y_pred,average='macro'))
print(f1_score(Y_test,Y_pred,average='macro'))

0.976
0.9777726955085445
0.9749002849002849
0.9759929612870788


In [100]:
Y_pred=vt_clf1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
print(precision_score(Y_val,Y_pred,average='macro'))
print(recall_score(Y_val,Y_pred,average='macro'))
print(f1_score(Y_val,Y_pred,average='macro'))


0.9574468085106383
0.9570401013714968
0.9607850707850707
0.9577831369906924


In [101]:
Y_pred=vt_clf1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))
print(precision_score(Y_train,Y_pred,average='macro'))
print(recall_score(Y_train,Y_pred,average='macro'))
print(f1_score(Y_train,Y_pred,average='macro'))

1.0
1.0
1.0
1.0


In [102]:
from sklearn.ensemble import BaggingClassifier
dt1=BaggingClassifier(n_estimators=50,max_samples=0.9,max_features=0.9)
timestart=time.time()
dt1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=dt1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

2.67899227142334
0.0383296012878418
0.992


In [103]:
Y_pred=dt1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=dt1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.973404255319149
1.0


In [104]:
svm1=BaggingClassifier(estimator=SVC(C=2.5),n_estimators=50,max_samples=0.9,max_features=0.9)
timestart=time.time()
svm1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=svm1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

1.5740902423858643
1.2292745113372803
0.864


In [105]:
Y_pred=svm1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=svm1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.851063829787234
0.928698752228164


In [106]:
logi1=BaggingClassifier(estimator=LogisticRegression(),n_estimators=50,max_samples=0.9,max_features=0.9)
timestart=time.time()
logi1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=logi1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

4.031424522399902
0.07168793678283691
0.968


In [107]:
Y_pred=logi1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=logi1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.973404255319149
0.9982174688057041


In [108]:
from sklearn.ensemble import RandomForestClassifier
rf1=RandomForestClassifier(n_estimators=50,max_samples=0.9,max_features=0.9,max_depth=15,criterion='gini')

In [109]:
timestart=time.time()
rf1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=rf1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

3.3227946758270264
0.005599498748779297
0.988


In [110]:
Y_pred=rf1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=rf1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.9680851063829787
1.0


In [111]:
from sklearn.ensemble import AdaBoostClassifier
ab1=AdaBoostClassifier(n_estimators=100,learning_rate=0.1)
timestart=time.time()
ab1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=ab1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

C:\Users\dss28\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


2.0610475540161133
0.016803741455078125
0.668


In [112]:
Y_pred=ab1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=ab1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.6170212765957447
0.7415329768270945


In [113]:
from sklearn.ensemble import GradientBoostingClassifier
gb1=GradientBoostingClassifier(n_estimators=100,subsample=0.9,max_features=0.9)
timestart=time.time()
gb1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=gb1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

12.175121068954468
0.020116329193115234
0.984


In [114]:
Y_pred=gb1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=gb1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.9680851063829787
1.0


In [115]:
from xgboost import XGBClassifier
xb1=XGBClassifier(n_estimators=100,subsample=0.9,max_features=0.9)
timestart=time.time()
xb1.fit(X_train,Y_train)
timeend=time.time()
print(timeend-timestart)
Y_pred=xb1.predict(X_test)
timeend2=time.time()
print(timeend2-timeend)
print(accuracy_score(Y_test,Y_pred))

C:\Users\dss28\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [18:47:31] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "max_features" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


2.0731587409973145
0.005180835723876953
0.984


In [116]:
Y_pred=xb1.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
Y_pred=xb1.predict(X_train)
print(accuracy_score(Y_train,Y_pred))

0.9680851063829787
1.0


In [117]:
# Y_pred=xb1.predict(X_train)
# print(accuracy_score(Y_train,Y_test))

In [118]:
estimators=[('dt1',dt1),('svm1',svm1),('logi1',logi1),('rf1',rf1),('ab1',ab1),('gb1',gb1),('xb1',xb1)]

In [119]:
vt_clf2=VotingClassifier(estimators=estimators,weights=[1.5,1,1.5,1.5,0.5,1.5,1.5])
vt_clf2.fit(X_train,Y_train)
Y_pred=vt_clf2.predict(X_test)
print(accuracy_score(Y_test,Y_pred))
print(precision_score(Y_test,Y_pred,average='macro'))
print(recall_score(Y_test,Y_pred,average='macro'))
print(f1_score(Y_test,Y_pred,average='macro'))

C:\Users\dss28\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\dss28\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:183: UserWarning: [18:47:55] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "max_features" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


0.992
0.9924528301886791
0.9925925925925926
0.9923802612481858


In [120]:
Y_pred=vt_clf2.predict(X_val)
print(accuracy_score(Y_val,Y_pred))
print(precision_score(Y_val,Y_pred,average='macro'))
print(recall_score(Y_val,Y_pred,average='macro'))
print(f1_score(Y_val,Y_pred,average='macro'))


0.9840425531914894
0.9860465116279069
0.9857142857142858
0.9853636769299421


In [121]:
# recall_score,f1_score,confusion_matrix
Y_pred=vt_clf2.predict(X_train)
print(accuracy_score(Y_train,Y_pred))
print(precision_score(Y_train,Y_pred,average='macro'))
print(recall_score(Y_train,Y_pred,average='macro'))
print(f1_score(Y_train,Y_pred,average='macro'))

1.0
1.0
1.0
1.0


In [122]:
test_array_list=[]
for test_path in test['path1']:
    test = cv2.imread(test_path)
    # print(img)
    if test is not None:
        # img = cv2.resize(img, (64, 64))
        test_array_list.append(test)
# img_path="kaggle/input/crop_images/jute/jute001a.jpeg"
# img1=cv2.imread(img_path)
test_array = np.array(test_array_list)   #input cols
test_array.shape

(10, 224, 224, 3)

In [123]:
# test=X_test.sample(5)
test_array=np.array([extract_color_histogram(img) for img in test_array])
test_array=scaler.transform(test_array)
vt_clf2.predict(test_array)

array([4, 3, 4, 0, 3, 4, 0, 4, 0, 4])

In [124]:
test1=pd.read_csv("test.csv")
test1

Sr       crop  crop_lablel                                  path
0    1  sugarcane            3    test_crop_image/sugarcane030a.jpeg
1    2  sugarcane            3    test_crop_image/sugarcane027a.jpeg
2    3      maize            1      test_crop_image/maize024ahf.jpeg
3    4       rice            2         test_crop_image/rice027a.jpeg
4    5      wheat            4        test_crop_image/wheat033a.jpeg
5    6       rice            2       test_crop_image/rice022ahf.jpeg
6    7      maize            1        test_crop_image/maize003a.jpeg
7    8      maize            1     test_crop_image/maize009arot.jpeg
8    9      wheat            4        test_crop_image/wheat016a.jpeg
9   10  sugarcane            3  test_crop_image/sugarcane034ahs.jpeg
10  11       jute            0        test_crop_image/juteleaves.jpg
11  12       rice            2      test_crop_image/rice-field01.jpg
12  13       jute            0           test_crop_image/jute003.jpg
13  14      maize            1         test_crop_image/maize000.jfif
14  15       jute            0        test_crop_image/jute-field.jpg
15  16  sugarcane            3  test_crop_image/sugarcane fields.jpg
16  17       jute            0           test_crop_image/juteimg.jpg
17  18      wheat            4     test_crop_image/wheat-field01.jpg
18  19       rice            2   test_crop_image/rice8122f869e3f.jpg
19  20      wheat            4        test_crop_image/wheat-crop.jpg

In [125]:
test1_array_list=[]
for test1_path in test1['path']:
    test1 = cv2.imread(test1_path)
    # print(img)
    if test1 is not None:
        test1 = cv2.resize(test1, (224, 224))
        test1_array_list.append(test1)
test1_array = np.array(test1_array_list)

In [126]:
test1_array=np.array([extract_color_histogram(img) for img in test1_array])

In [127]:
test1_array=scaler.transform(test1_array)
vt_clf2.predict(test1_array)

array([3, 3, 1, 2, 4, 2, 1, 1, 4, 3, 0, 2, 0, 0, 1, 1, 2, 2, 0, 4])